site_name: SAGE Edu – Documentação
site_url: https://<seu-usuario>.github.io/sage-edu-docs/

theme:
  name: 'readthedocs'
  language: 'pt'
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Manual do Utilizador:
    - Guia do Sistema:
      - Introdução: guia/intro.md
      - Instalação: guia/install.md
      - Primeiros Passos: 
        - Demonstração: guia/demo.md
        - Interface Gráfica: guia/interface.md
    - Módulos: 
      - SGA: 
        - Descrição: modulos/sga/intro.md
        - Entidades: modulos/sga/party.md
        - Matrículas: modulos/sga/matriculation.md
        - Turmas: modulos/sga/classes.md
        - Avaliações: modulos/sga/avaliation.md
        - Configurações: modulos/sga/configuration.md
      - SGE: modulos/sge.md
      - SIE: modulos/sie.md