site_name: SAGE Edu – Documentação
site_url: https://<seu-usuario>.github.io/sage-edu-docs/

theme:
  name: 'readthedocs'
  language: 'en'
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Introduction: guia/intro.md
  - Quick Guide:
    - Demonstration: guia/demo.md
    - Installation: guia/install.md
    - System Interface: guia/interface.md
  - Modules: 
    - SGA: 
      - Description: modulos/sga/intro.md
      - Entities: modulos/sga/party.md
      - Matriculations: modulos/sga/matriculation.md
      - Classes: modulos/sga/classes.md
      - Avaliations: modulos/sga/avaliation.md
      - Configurations: modulos/sga/configuration.md
    - SGE: 
      - Description: modulos/sge/intro.md
    - SIE: 
      - Description: modulos/sie/intro.md
  #- Manual do Utilizador: 
    #- Perfis de Acesso: guia/perfis.md
    #- Fluxo de Operações: guia/conceitos.md 
  #- Administração do Sistema:
  #  - Configurações Globais: admin/config.md
  #  - Utilizadores e Permissões (ACL): admin/users.md
  #  - Backup e Recuperação: admin/backup.md
  #  - Auditoria e Logs: admin/audit.md
  - Desenvolvedor:
    - Processo de Desenvolvimento: guia/relaese_process.md
    - Ambiente de Desenvolvimento: guia/dev.md
    - Contrinuições: guia/contributing.md
  #    - API: api/index.md
  #    - Base de Dados: dev/db.md
  #    - Integrações: dev/integrations.md

  #- Suporte:
  #    - Perguntas Frequentes: suporte/faq.md
  #    - Problemas Comuns: suporte/troubleshooting.md