site_name: SAGE Edu – Documentação
site_url: https://<seu-usuario>.github.io/sage-edu-docs/

theme:
  name: 'readthedocs'
  language: 'pt'
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Manual do Utilizador:
    - Guia do Sistema:
        - Introdução: guia/introducao.md
        - Instalação: guia/instalacao.md
        - Primeiros Passos: guia/primeiros-passos.md
        - Módulos: guia/modulos.md
    - Menu:
        - SGA: modulos/sga.md
        - SGE: modulos/sge.md
        - SIE: modulos/sie.md