site_name: SAGE Edu – Documentação
site_url: https://<seu-usuario>.github.io/sage-edu-docs/

theme:
  name: 'readthedocs'
  language: 'pt'
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Introdução: guia/intro.md
  - Guia Rápido:
    - Demonstração: guia/demo.md
    - Instalação: guia/install.md
    - Interface do Sistema: guia/interface.md
  - Módulos: 
    - SGA: 
      - Descrição: modulos/sga/intro.md
      - Entidades: modulos/sga/party.md
      - Matrículas: modulos/sga/matriculation.md
      - Turmas: modulos/sga/classes.md
      - Avaliações: modulos/sga/avaliation.md
      - Configurações: modulos/sga/configuration.md
    - SGE: 
      - Descrição: modulos/sge/intro.md
    - SIE: 
      - Descrição: modulos/sie/intro.md
  #- Manual do Utilizador: 
    #- Perfis de Acesso: guia/perfis.md
    #- Fluxo de Operações: guia/conceitos.md 
  #- Administração do Sistema:
  #  - Configurações Globais: admin/config.md
  #  - Utilizadores e Permissões (ACL): admin/users.md
  #  - Backup e Recuperação: admin/backup.md
  #  - Auditoria e Logs: admin/audit.md
  - Desenvolvedor:
    - Processo de Desenvolvimento: guia/relaese_process.md
    - Ambiente de Desenvolvimento: guia/dev.md
  #    - API: api/index.md
  #    - Base de Dados: dev/db.md
  #    - Integrações: dev/integrations.md

  #- Suporte:
  #    - Perguntas Frequentes: suporte/faq.md
  #    - Problemas Comuns: suporte/troubleshooting.md